FIRST_NAMES = [
    # "An", "Bảo", "Chi", "Dũng", "Giang", "Hải", "Hương", "Khánh", "Linh", "Minh", "Nam", "Nga", "Phúc", "Quân", "Sơn", "Thảo", "Trang", "Việt", "Tùng", "Mai",
    "James", "Mary", "John", "Patricia", "Robert", "Jennifer", "Michael", "Linda",
    "William", "Elizabeth", "David", "Barbara", "Richard", "Susan", "Joseph", "Jessica",
    "Thomas", "Sarah", "Charles", "Karen", "Christopher", "Nancy", "Daniel", "Lisa",
    "Matthew", "Margaret", "Anthony", "Betty", "Mark", "Sandra", "Donald", "Ashley",
    "Steven", "Kimberly", "Paul", "Donna", "Andrew", "Emily", "Joshua", "Michelle",
    "Kevin", "Dorothy", "Brian", "Amanda", "George", "Helen", "Edward", "Melissa",
    "Ronald", "Deborah", "Timothy", "Stephanie", "Jason", "Laura", "Jeffrey", "Rebecca",
    "Ryan", "Sharon", "Jacob", "Cynthia", "Gary", "Kathleen", "Nicholas", "Amy",
    "Eric", "Shirley", "Stephen", "Angela", "Jonathan", "Anna", "Larry", "Ruth",
    "Justin", "Brenda", "Scott", "Pamela", "Brandon", "Nicole", "Benjamin", "Katherine",
    "Samuel", "Samantha", "Gregory", "Christine", "Frank", "Catherine", "Alexander", "Virginia",
    "Patrick", "Debra", "Raymond", "Rachel", "Jack", "Janet", "Dennis", "Emma",
    "Jerry", "Carolyn", "Tyler", "Maria", "Aaron", "Heather", "Jose", "Diane",
    "Adam", "Julie", "Henry", "Joyce", "Nathan", "Victoria", "Douglas", "Olivia",
    "Zachary", "Kelly", "Peter", "Christina", "Kyle", "Lauren", "Walter", "Joan",
    "Ethan", "Evelyn", "Jeremy", "Judith", "Harold", "Megan", "Keith", "Cheryl",
    "Christian", "Andrea", "Roger", "Hannah", "Noah", "Martha", "Gerald", "Jacqueline",
    "Carl", "Frances", "Terry", "Gloria", "Sean", "Ann", "Austin", "Teresa",
    "Arthur", "Kathryn", "Lawrence", "Sara", "Jesse", "Janice", "Dylan", "Jean",
    "Bryan", "Alice", "Joe", "Madison", "Jordan", "Doris", "Billy", "Abigail",
    "Bruce", "Julia", "Albert", "Judy", "Willie", "Grace", "Gabriel", "Denise",
    "Logan", "Amber", "Alan", "Marilyn", "Juan", "Danielle", "Wayne", "Beverly",
    "Roy", "Diana", "Ralph", "Theresa", "Randy", "Sophia", "Eugene", "Marie",
    "Vincent", "Rose", "Russell", "Isabella", "Elijah", "Charlotte", "Louis", "Natalie"
]

LAST_NAMES = [
    # "Nguyễn", "Trần", "Lê", "Phạm", "Hoàng", "Huỳnh", "Phan", "Vũ", "Võ", "Đặng", "Bùi", "Đỗ", "Hồ", "Ngô", "Dương",
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis",
    "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson",
    "Thomas", "Taylor", "Moore", "Jackson", "Martin", "Lee", "Perez", "Thompson",
    "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson", "Walker",
    "Young", "Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill",
    "Flores", "Green", "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell",
    "Mitchell", "Carter", "Roberts", "Gomez", "Phillips", "Evans", "Turner", "Diaz",
    "Parker", "Cruz", "Edwards", "Collins", "Reyes", "Stewart", "Morris", "Morales",
    "Murphy", "Cook", "Rogers", "Gutierrez", "Ortiz", "Morgan", "Cooper", "Peterson",
    "Bailey", "Reed", "Kelly", "Howard", "Ramos", "Kim", "Cox", "Ward",
    "Richardson", "Watson", "Brooks", "Chavez", "Wood", "James", "Bennett", "Gray",
    "Mendoza", "Ruiz", "Hughes", "Price", "Alvarez", "Castillo", "Sanders", "Patel",
    "Myers", "Long", "Ross", "Foster", "Jimenez", "Powell", "Jenkins", "Perry",
    "Russell", "Sullivan", "Bell", "Coleman", "Butler", "Henderson", "Barnes", "Gonzales",
    "Fisher", "Vasquez", "Simmons", "Romero", "Jordan", "Patterson", "Alexander", "Hamilton"
]

MASSIVE_CONTENT_THEMES = [
    # --- Chủ đề: Technology (15 posts) ---
    {"topic": "technology", "content": "My review of the M4 MacBook Pro: Is the performance jump worth the price? #MacBookPro #M4 #Apple"},
    {"topic": "technology","content": "The ethical implications of AI are getting more complex. We need to talk about regulation. #AIEthics #FutureTech"},
    {"topic": "technology", "content": "I built my own home server using a Raspberry Pi. Here's how you can do it too! #DIYTech #RaspberryPi #HomeServer"},
    {"topic": "technology", "content": "Cloudflare is down, and half the internet seems to be broken. #Cloudflare #InternetDown"},
    {"topic": "technology", "content": "Just tried the new VR headset from Meta. The immersion is next-level. #VR #MetaQuest #VirtualReality"},
    {"topic": "technology", "content": "Why are big tech companies all laying off staff amidst record profits? #TechIndustry #Layoffs"},
    {"topic": "technology", "content": "A beginner's guide to understanding blockchain beyond just cryptocurrency. #Blockchain #Web3"},
    {"topic": "technology", "content": "The new update for my phone is draining the battery like crazy. Anyone else? #iOS18 #Bug #TechSupport"},
    {"topic": "technology", "content": "This password manager just saved me. Stop reusing passwords! #Cybersecurity #PasswordManager"},
    {"topic": "technology", "content": "My minimalist desk setup for maximum productivity. #DeskSetup #WFH #Tech"},
    {"topic": "technology", "content": "I'm learning Rust, and it's challenging but so powerful. #RustLang #Programming"},
    {"topic": "technology", "content": "The race for Quantum Supremacy is heating up between Google and IBM. #QuantumComputing #Science"},
    {"topic": "technology", "content": "Remember foldable phones? I'm still not convinced they're the future. #FoldablePhone #Samsung"},
    {"topic": "technology", "content": "Starlink just rolled out a new mini dish. This is a game-changer for travelers. #Starlink #SpaceX #Internet"},
    {"topic": "technology", "content": "Why I'm switching from Chrome to Firefox (again). Hint: Privacy. #Firefox #Browser #Privacy"},

    # --- Chủ đề: Travel (15 posts) ---
    {"topic": "travel", "content": "Lost in the streets of Rome. Every corner is a piece of history. #Italy #Rome #Travel"},
    {"topic": "travel", "content": "The street food in Hanoi, Vietnam, is on another level. Bún Chả for breakfast! #Vietnam #Hanoi #StreetFood"},
    {"topic": "travel", "content": "Pro tip: Always roll your clothes when packing. Saves so much space. #TravelHack #Packing"},
    {"topic": "travel", "content": "Waking up in a traditional Ryokan in Japan is an experience I'll never forget. #Japan #Kyoto #Ryokan"},
    {"topic": "travel", "content": "Finally saw the Northern Lights in Iceland! Bucket list item checked. #Iceland #NorthernLights #AuroraBorealis"},
    {"topic": "travel", "content": "The hike to Machu Picchu was grueling but the sunrise view was worth every step. #Peru #MachuPicchu #Hiking"},
    {"topic": "travel", "content": "How to budget for a trip to Europe without breaking the bank. #EuropeTravel #BudgetTravel"},
    {"topic": "travel", "content": "Solo travel is intimidating at first, but it's the most rewarding way to see the world. #SoloTravel #Wanderlust"},
    {"topic": "travel", "content": "My flight just got delayed by 6 hours. The airport life... #TravelProblems #Delayed"},
    {"topic": "travel", "content": "Exploring the souks of Marrakech. A sensory overload in the best way possible. #Morocco #Marrakech #Travel"},
    {"topic": "travel", "content": "The beaches in the Philippines are just unreal. Palawan is paradise. #Philippines #Palawan #BeachLife"},
    {"topic": "travel", "content": "What's one travel accessory you can't live without? For me, it's noise-canceling headphones. #TravelGear"},
    {"topic": "travel", "content": "Driving the Great Ocean Road in Australia. Stunning coastal views. #Australia #RoadTrip"},
    {"topic": "travel", "content": "Trying to learn basic Spanish before my trip to Colombia. 'Una cerveza, por favor!' #TravelPrep #LanguageLearning"},
    {"topic": "travel", "content": "The best travel insurance might be the one you already have with your credit card. Check it! #TravelTips #Finance"},

    # --- Chủ đề: Food (15 posts) ---
    {"topic": "food", "content": "I think I just made the perfect chocolate chip cookie. The secret is browned butter. #Baking #Cookies #Recipe"},
    {"topic": "food", "content": "This hole-in-the-wall ramen shop is a hidden gem. Best tonkotsu broth ever. #Ramen #Foodie #Japan"},
    {"topic": "food", "content": "I'm trying to eat less meat. Any good plant-based recipes? #PlantBased #Vegan #Cooking"},
    {"topic": "food", "content": "Air fryer is a game changer. Crispy sweet potato fries with zero oil. #AirFryer #HealthyEating"},
    {"topic": "food", "content": "Finally got a reservation at that new sushi place. Omakase, here I come! #Sushi #Omakase #FineDining"},
    {"topic": "food", "content": "My controversial food opinion: pineapple belongs on pizza. #PineapplePizza #FoodDebate"},
    {"topic": "food", "content": "How to make the perfect poached egg. It's all about the vinegar swirl. #Breakfast #CookingTips"},
    {"topic": "food", "content": "This farmers' market has the freshest strawberries I've ever tasted. #FarmersMarket #Organic #Food"},
    {"topic": "food", "content": "Trying to recreate the pasta I had in Italy. It's just not the same. #ItalianFood #Pasta"},
    {"topic": "food", "content": "Late-night snack: Instant noodles with a slice of cheese and a soft-boiled egg. #LateNight #Snack"},
    {"topic": "food", "content": "My coffee setup: V60 pour-over. It's a peaceful morning ritual. #Coffee #V60 #SpecialtyCoffee"},
    {"topic": "food", "content": "Just finished meal-prepping for the entire week. My future self will thank me. #MealPrep #HealthyLifestyle"},
    {"topic": "food", "content": "The spice blend on this biryani is incredible. South Asian food is simply the best. #IndianFood #Biryani"},
    {"topic": "food", "content": "I'm addicted to this spicy chili crisp. I put it on everything! #ChiliOil #Condiments"},
    {"topic": "food", "content": "Learning how to properly sharpen my kitchen knives. It makes a huge difference. #KitchenSkills #Cooking"},

    # --- Chủ đề: Sports (15 posts) ---
    {"topic": "sports", "content": "What a final! That match had everything. Incredible performance from both teams. #Football #ChampionsLeague"},
    {"topic": "sports", "content": "My fantasy football team is in shambles after all these injuries. #FantasyFootball #NFL"},
    {"topic": "sports", "content": "The trade deadline in the NBA was wild! Can't believe he got traded. #NBA #TradeDeadline"},
    {"topic": "sports", "content": "Just watched the F1 race. The strategy battle was more exciting than the overtakes. #F1 #Formula1 #Racing"},
    {"topic": "sports", "content": "This rookie is playing like a 10-year veteran. Unbelievable talent. #Baseball #MLB"},
    {"topic": "sports", "content": "Another marathon in the books! Didn't hit my PR, but I finished. #Marathon #Running"},
    {"topic": "sports", "content": "Is pickleball the fastest-growing sport? Everyone I know is playing it. #Pickleball #SportsTrend"},
    {"topic": "sports", "content": "That was a clear penalty! How did the referee miss that? #VAR #Football #PremierLeague"},
    {"topic": "sports", "content": "The Olympics are next year! Which new sport are you most excited to watch? #Olympics #Paris2024"},
    {"topic": "sports", "content": "Just signed up for a jiu-jitsu class. Time to get humbled. #BJJ #MartialArts #Fitness"},
    {"topic": "sports", "content": "The Tour de France is such an insane endurance test. #Cycling #TDF2024"},
    {"topic": "sports", "content": "My GOAT debate: Jordan or LeBron? Let's discuss. #NBA #Basketball #GOAT"},
    {"topic": "sports", "content": "UFC main event was a banger! What a knockout. #UFC #MMA"},
    {"topic": "sports", "content": "Trying to improve my golf swing. It's endlessly frustrating. #Golf #Fore"},
    {"topic": "sports", "content": "Congratulations to Nadal on another French Open. Truly the King of Clay. #Tennis #RolandGarros"},

    # --- Chủ đề: Finance (15 posts) ---
    {"topic": "finance", "content": "Just maxed out my Roth IRA for the year. Feels good. #Investing #Retirement #FinancialFreedom"},
    {"topic": "finance", "content": "The stock market is a rollercoaster. Just holding my index funds and not looking. #Investing #Stocks #DCA"},
    {"topic": "finance", "content": "This inflation is brutal. My grocery bill is 30% higher than last year. #Inflation #Economy"},
    {"topic": "finance", "content": "Is a high-yield savings account (HYSA) the best place for an emergency fund right now? #HYSA #Banking #PersonalFinance"},
    {"topic": "finance", "content": "Trying to get my credit score above 800. Almost there! #CreditScore #FinanceTips"},
    {"topic": "finance", "content": "Bitcoin is pumping again. Are we back in a bull market? #Crypto #Bitcoin"},
    {"topic": "finance", "content": "I just paid off my student loans! I can't believe it's finally done. #StudentLoans #DebtFree"},
    {"topic": "finance", "content": "Real estate interest rates are making it impossible for first-time home buyers. #RealEstate #HousingMarket"},
    {"topic": "finance", "content": "My 'no-buy' month was a success! Saved a lot of money by not buying wants. #Budgeting #Minimalism"},
    {"topic": "finance", "content": "What are your favorite budgeting apps? I've been using YNAB. #Budget #YNAB #Fintech"},
    {"topic": "finance", "content": "Diversification is key. Don't put all your eggs in one basket (or one stock). #Investing101"},
    {"topic": "finance", "content": "The Fed is expected to raise rates again. Bad news for borrowers. #FederalReserve #Economy"},
    {"topic": "finance", "content": "What's the difference between a 401k and an IRA? #Retirement #Investing"},
    {"topic": "finance", "content": "This credit card has the best travel rewards. The annual fee is worth it. #CreditCards #TravelHacking"},
    {"topic": "finance", "content": "Side hustle update: My small business finally turned a profit this month! #SideHustle #Entrepreneur"},

    # --- Chủ đề: Wellness (15 posts) ---
    {"topic": "wellness", "content": "My morning meditation practice has changed my life. 10 minutes of calm. #Meditation #Mindfulness"},
    {"topic": "wellness", "content": "Remember to hydrate! Drinking enough water is the easiest health win. #Health #Wellness #Hydration"},
    {"topic": "wellness", "content": "I'm taking a social media detox for the weekend. Need to reset my brain. #DigitalDetox #MentalHealth"},
    {"topic": "wellness", "content": "Just finished a 7-day yoga challenge. Feeling so much more flexible. #Yoga #Fitness"},
    {"topic": "wellness", "content": "The importance of sleep is underrated. Aiming for 8 hours every night. #Sleep #Health"},
    {"topic": "wellness", "content": "Journaling my thoughts before bed helps me clear my mind. #Journaling #SelfCare"},
    {"topic": "wellness", "content": "My new standing desk is helping my back pain so much. #WFH #Ergonomics #Wellness"},
    {"topic": "wellness", "content": "What are your favorite healthy snacks? I'm stuck on almonds and apples. #HealthyEating #Snacks"},
    {"topic": "wellness", "content": "A simple gratitude practice: Write down 3 things you're thankful for. #Gratitude #MentalWellness"},
    {"topic": "wellness", "content": "I finally went to therapy, and it's not as scary as I thought. #Therapy #MentalHealthAwareness"},
    {"topic": "wellness", "content": "Taking a cold plunge every morning. It's brutal but the energy boost is real. #ColdPlunge #WimHof"},
    {"topic": "wellness", "content": "My screen time report is shocking. Need to reduce this. #DigitalWellness #PhoneAddiction"},
    {"topic": "wellness", "content": "Learning about gut health and probiotics. It's all connected. #GutHealth #Wellness"},
    {"topic": "wellness", "content": "A long walk in nature is the best cure for a stressful day. #Nature #Walking #MentalHealth"},
    {"topic": "wellness", "content": "Setting boundaries is a form of self-care. It's okay to say no. #SelfCare #Boundaries"},

    # --- Chủ đề: Entertainment (Movies/TV/Music) (15 posts) ---
    {"topic": "entertainment", "content": "This new Netflix show is incredible. I can't stop watching. #Netflix #BingeWatching"},
    {"topic": "entertainment", "content": "Just saw the 'Joker 2' trailer. It looks... interesting. #Joker2 #MovieTrailer"},
    {"topic": "entertainment", "content": "Oppenheimer or Barbie? Which one was the better movie? #Barbenheimer #Movies"},
    {"topic": "entertainment", "content": "I'm creating a playlist for a road trip. What songs are a must-have? #Music #Playlist #RoadTrip"},
    {"topic": "entertainment", "content": "This new album from Kendrick Lamar is pure art. So many layers. #KendrickLamar #Music #HipHop"},
    {"topic": "entertainment", "content": "Why do they keep rebooting classic movies? Just make something original! #Hollywood #Movies"},
    {"topic": "entertainment", "content": "The series finale of 'Succession' was perfect. No notes. #Succession #HBO #TV"},
    {"topic": "entertainment", "content": "Going to a live concert tonight! There's nothing like live music. #Concert #LiveMusic"},
    {"topic": "entertainment", "content": "What's a movie that everyone loves but you just can't get into? #UnpopularOpinion #Movies"},
    {"topic": "entertainment", "content": "Spotify's algorithm knows me better than I know myself. #Spotify #MusicDiscovery"},
    {"topic": "entertainment", "content": "A24 just released another beautiful, weird, and confusing film. I loved it. #A24 #IndieFilm"},
    {"topic": "entertainment", "content": "The new season of 'The Bear' is giving me so much anxiety, but it's brilliant. #TheBear #TVShow"},
    {"topic": "entertainment", "content": "My vinyl collection is growing. Just found a rare pressing. #Vinyl #MusicCollector"},
    {"topic": "entertainment", "content": "Hot take: The book was way better than the movie. #Books #MovieAdaptation"},
    {"topic": "entertainment", "content": "This true crime documentary is chilling. I can't believe it's a true story. #TrueCrime #Netflix"},

    # --- Chủ đề: Fashion & Lifestyle (15 posts) ---
    {"topic": "fashion", "content": "New sneaker pickup! The quality on these is amazing. #Sneakers #Nike #OOTD"},
    {"topic": "fashion", "content": "Is fast fashion really worth the environmental cost? Trying to buy more secondhand. #SustainableFashion #Thrifting"},
    {"topic": "fashion", "content": "My outfit of the day. Keeping it simple and classic. #OOTD #Fashion #Minimalist"},
    {"topic": "fashion", "content": "The 'Old Money' aesthetic is all over my feed. What do you think of this trend? #OldMoney #StyleTrend"},
    {"topic": "fashion", "content": "Just bought a new watch. It's a timeless piece. #Watch #Horology #Style"},
    {"topic": "lifestyle", "content": "My cozy reading corner is finally complete. #HomeDecor #ReadingNook #Cozy"},
    {"topic": "lifestyle", "content": "This new cafe has the best interior design and great coffee. #Cafe #Aesthetic #Lifestyle"},
    {"topic": "fashion", "content": "Learning how to sew to mend my own clothes. #DIY #Sewing #SustainableLiving"},
    {"topic": "fashion", "content": "What's your go-to perfume? I'm looking for a new signature scent. #Perfume #Fragrance"},
    {"topic": "fashion", "content": "A good pair of jeans is the foundation of any wardrobe. #Denim #FashionTips"},
    {"topic": "lifestyle", "content": "I'm trying to become a plant parent. Any tips for not killing a fern? #Plants #IndoorGarden"},
    {"topic": "lifestyle", "content": "My minimalist apartment tour. Less stuff, more peace. #Minimalism #ApartmentLiving"},
    {"topic": "fashion", "content": "The Met Gala themes are getting weirder every year. #MetGala #Fashion"},
    {"topic": "lifestyle", "content": "Waking up at 5 AM has been a game-changer for my productivity. #5amClub #MorningRoutine"},
    {"topic": "lifestyle", "content": "I'm officially a dog owner! Meet my new best friend. #Dog #Pets #Lifestyle"},

    # --- Chủ đề: Science & Nature (15 posts) ---
    {"topic": "science", "content": "The James Webb Telescope images are just breathtaking. We are so small. #JWST #Space #Astronomy"},
    {"topic": "science", "content": "They just discovered a new species of deep-sea creature. It looks like an alien. #MarineBiology #Science"},
    {"topic": "nature", "content": "Hiking in the national park this weekend. Disconnecting from tech. #Hiking #Nature #Outdoors"},
    {"topic": "science", "content": "What is 'dark matter' and why can't we find it? #Physics #Space #ScienceExplained"},
    {"topic": "nature", "content": "Mushroom foraging is my new hobby. It's like a treasure hunt. #Foraging #Mushrooms #Nature"},
    {"topic": "science", "content": "CRISPR gene editing is progressing so fast. The ethical questions are huge. #CRISPR #Bioethics #Genetics"},
    {"topic": "nature", "content": "The cherry blossoms are in full bloom. My favorite time of year. #CherryBlossoms #Spring #Nature"},
    {"topic": "science", "content": "A total solar eclipse is happening next month! Who's in the path of totality? #Eclipse #Astronomy"},
    {"topic": "nature", "content": "The sound of rain on the window is the most relaxing thing. #Rain #Cozy #Nature"},
    {"topic": "science", "content": "I'm obsessed with watching videos about ocean conservation. We need to protect our reefs. #Ocean #Conservation"},
    {"topic": "nature", "content": "This national park has zero light pollution. The stars are unbelievable. #Stargazing #Astrophotography"},
    {"topic": "science", "content": "The intelligence of crows and ravens is fascinating. They can solve complex puzzles. #Birds #Ornithology"},
    {"topic": "science", "content": "What was the 'Big Bang'? A simple breakdown. #Cosmology #Science"},
    {"topic": "nature", "content": "Just saw a whale breach! An absolutely magical moment. #WhaleWatching #Nature"},
    {"topic": "nature", "content": "Started a small vegetable garden on my balcony. #Gardening #UrbanGardening"},

    # --- Chủ đề: Gaming (15 posts) ---
    {"topic": "gaming", "content": "Just hit 100 hours in Baldur's Gate 3 and I'm still in Act 1. This game is massive. #BG3 #Gaming #RPG"},
    {"topic": "gaming", "content": "The new GTA 6 trailer broke the internet. The graphics look insane. #GTA6 #RockstarGames"},
    {"topic": "gaming", "content": "My 'cozy game' of choice is Stardew Valley. It's so relaxing. #StardewValley #CozyGaming"},
    {"topic": "gaming", "content": "I miss the days of split-screen multiplayer on the couch. #RetroGaming #Nostalgia"},
    {"topic": "gaming", "content": "This new indie game is a hidden gem. Don't sleep on it! #IndieGaming #Gaming"},
    {"topic": "gaming", "content": "My gaming backlog is out of control. I keep buying games and not playing them. #SteamSale #GamerProblems"},
    {"topic": "gaming", "content": "Finally beat that boss in Elden Ring. My hands are shaking. #EldenRing #FromSoftware"},
    {"topic": "gaming", "content": "My team and I won the local Valorant tournament! #Valorant #Esports #Gaming"},
    {"topic": "gaming", "content": "What's a game that was a 10/10 for you? For me, it's The Last of Us. #Gaming #PS5"},
    {"topic": "gaming", "content": "This gaming chair was a good investment. My back is thankful. #GamingSetup #PCGaming"},
    {"topic": "gaming", "content": "The storytelling in 'Red Dead Redemption 2' is on another level. #RDR2 #Gaming"},
    {"topic": "gaming", "content": "Why are video game file sizes so enormous now? My hard drive is full. #Gaming #PCMasterRace"},
    {"topic": "gaming", "content": "Hades 2 is finally out in early access! #Hades2 #SupergiantGames #IndieGaming"},
    {"topic": "gaming", "content": "Just built my new PC. The cable management was a nightmare, but it's done! #PCBuilding #GamingPC"},
    {"topic": "gaming", "content": "Is the Nintendo Switch 2 coming out soon? The rumors are flying. #NintendoSwitch #GamingNews"},

    # --- Chủ đề: Art & Design (15 posts) ---
    {"topic": "art", "content": "Visited the Museum of Modern Art (MoMA) today. 'Starry Night' is even more beautiful in person. #MoMA #Art #VanGogh"},
    {"topic": "design", "content": "This brand's packaging is a 10/10. Great design makes a difference. #Packaging #Design #Branding"},
    {"topic": "art", "content": "My latest watercolor painting. Still learning how to control the water. #Watercolor #Art #Painting"},
    {"topic": "design", "content": "I love brutalist architecture. I know it's not for everyone, but it's so bold. #Brutalism #Architecture"},
    {"topic": "art", "content": "This street art I found is incredible. #StreetArt #Graffiti #UrbanArt"},
    {"topic": "design", "content": "Redesigning my portfolio website. Trying to keep it clean and simple. #WebDesign #UIUX #Figma"},
    {"topic": "art", "content": "Learning about color theory. It's amazing how colors can affect mood. #ColorTheory #ArtSchool"},
    {"topic": "art", "content": "I'm trying 'plein air' painting (painting outdoors). It's harder than it looks! #PleinAir #Painting"},
    {"topic": "design", "content": "The new IKEA collection has some surprisingly good-looking pieces. #IKEA #InteriorDesign #Furniture"},
    {"topic": "design", "content": "Good typography is invisible, but bad typography is everywhere. #Typography #GraphicDesign"},
    {"topic": "art", "content": "Just started learning pottery. Throwing on the wheel is so therapeutic. #Pottery #Ceramics #Art"},
    {"topic": "design", "content": "This app has a terrible user experience. It's so confusing. #UX #UIDesign #BadDesign"},
    {"topic": "art", "content": "The \"Art Deco\" style of the 1920s is one of my favorites. #ArtDeco #History #Design"},
    {"topic": "art", "content": "My digital art setup: iPad Pro + Procreate. It's a game-changer. #DigitalArt #Procreate"},
    {"topic": "design", "content": "A great logo looks simple, but it's incredibly hard to design. #LogoDesign #Branding"},

    # --- Chủ đề: Career & Business (15 posts) ---
    {"topic": "career", "content": "Just aced my job interview! Fingers crossed I get the offer. #JobInterview #Career #Hustle"},
    {"topic": "business", "content": "My small business just made its 100th sale! Thank you to everyone who supported. #SmallBusiness #Entrepreneur"},
    {"topic": "career", "content": "Dealing with burnout is tough. Remember to take your PTO. #Burnout #WorkLifeBalance"},
    {"topic": "business", "content": "Why 'company culture' is more than just free snacks and a ping-pong table. #CompanyCulture #Leadership"},
    {"topic": "career", "content": "I'm negotiating my salary for the first time. Any tips? #SalaryNegotiation #CareerAdvice"},
    {"topic": "career", "content": "Learning to code to switch careers. It's never too late. #CareerChange #Coding"},
    {"topic": "business", "content": "Marketing is not just advertising, it's about telling a good story. #Marketing #Branding #Storytelling"},
    {"topic": "career", "content": "My manager is a great leader, not just a boss. It makes all the difference. #Leadership #Work"},
    {"topic": "business", "content": "This AI tool is saving my business hours of work every week. #AI #Productivity #Automation"},
    {"topic": "career", "content": "The best career advice I ever got: 'Always be learning.' #CareerDevelopment #GrowthMindset"},
    {"topic": "business", "content": "Networking is scary, but it's essential for growing your business. #Networking #Entrepreneurship"},
    {"topic": "career", "content": "I'm working remotely, and I don't think I can ever go back to an office. #RemoteWork #WFH"},
    {"topic": "business", "content": "Cash flow is the lifeblood of a small business. Learning this the hard way. #Business101 #Finance"},
    {"topic": "career", "content": "My LinkedIn profile is finally updated. It's so hard to write about yourself. #LinkedIn #PersonalBranding"},
    {"topic": "career", "content": "I finally quit the toxic job. My mental health is already improving. #ToxicWorkplace #CareerMove"}
]